### ISSUE TITLE
Arduino UNO - ERR

### ISSUE THREAD

**Issue by kksbolash** [pololu/qik-arduino#1]
Hi.
I am testing your library with an Arduino UNO, and qik 2s9v1 …
The connections seem to be okay.
Heartbeat green LED is spinning at .4s as indicated in docs.
Library compiles and uploads okay.
But as soon as the code runs it is triggering the red LED, which simply stays lit.
I am running the Qik2s9v1Demo project.
And for example, no firmware version is output etc.
I have tried getErrors(), but nothing returned on that either.

**Comment by ryantm** [comment]
Hello.

We use GitHub Issues for library development and library bug reports. For general troubleshooting, please use our regular support channels at https://www.pololu.com/support.

When you contact support, please include a photo of your setup and a description of all of your wiring connections.

Ryan
